spring:
 profiles:
  active: development
   
server:
 port: 8060

datasource :
 driverClassName: com.mysql.jdbc.Driver
 host: localhost
 port: 3306
 dataBaseName: bbt_development
 username: root
 password: admin123
 hibernateProps: 
  hibernate.hbm2ddl.auto : create-drop
  hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
 client:
  serviceUrl:
   defaultZone: http://127.0.0.1:8761/eureka/

---
spring:
  profiles: cloud
eureka:
 instance:
  hostname: localhost
  nonSecurePort: 80
    

 
  
