server:
 port: ${vcap.application.port:8761}
  
eureka:
 instance:
  hostname: localhost
 client:
  registerWithEureka: false
  fetchRegistry: false
  server:waitTimeInMsWhenSyncEmpty: 0
  metadataMap:
   instanceId:
    ${spring.application.name}: ${spring.application.instance_id:${server.port}}
